LANGCODE = {
	'English - United States': 'en',
	'Spanish': 'es',
	'Arabic': 'ar',
	'Arabic - Saudi Arabia': 'ar',
	'China': 'zh-cn',
	'Chinese (Simplified) - People\'s Republic of China': 'zh-cn',
	'Twi': 'zh-tw',
	'Chinese (Traditional) - Taiwan': 'zh-tw',
	'Danish': 'da',
	'Czech'    : 'CS',
	'Czech - Czech Republic'    : 'CS',
	'Danish'   : 'DA',
	'Danish - Denmark'   : 'DA',
	'Dutch'    : 'NL',
	'Dutch - Netherlands'    : 'NL',
	'English'  : 'EN',
	'Finnish'  : 'FI',
	'Finnish - Finland'  : 'FI',
	'French'   : 'FR',
	'French - France'   : 'FR',
	'German'   : 'DE',
	'German - Germany'   : 'DE',
	'Greek'    : 'EL',
	'Greek - Greece'    : 'EL',
	'Hebrew'   : 'HE',
	'Hebrew - Israel'   : 'HE',
	'Hungarian': 'HU',
	'Hungarian - Hungary': 'HU',
	'Italian'  : 'IT',
	'Italian - Italy'  : 'IT',
	'Japanese' : 'JA',
	'Japanese - Japan' : 'JA',
	'Korean'   : 'KO',
	'Korean - Korea'   : 'KO',
	'Norwegian': 'NO',
	'Norwegian (Bokmal) - Norway': 'NO',
	'Polish'   : 'PL',
	'Polish - Poland'   : 'PL',
	'Russian'  : 'RU',
	'Russian - Russia'  : 'RU',
	'Slovak'   : 'SK',
	'Slovak - Slovakia'   : 'SK',
	'Slovene': 'SL',
	'Slovenian - Slovenia': 'SL',
	'Spanish'  : 'ES',
	'Spanish - Spain'  : 'ES',
	'Swedish'  : 'SV',
	'Swedish - Sweden'  : 'SV',
	'Turkish'  : 'TR',
	'Turkish - Turkey'  : 'TR',
	'Portuguese - Brazil': 'PT-BR',
	'Portuguese': 'PT-PT',
	'Portuguese - Portugal': 'PT-PT',
}
LANGCODE = {
	k.lower(): v.lower() for k, v in LANGCODE.items()
}
